### ISSUE TITLE
Binary search problems solution in Java

### ISSUE THREAD

**Issue by anantnipunge** [akshay2742/Hacktoberfest2022#51]
here i want to add binary search problem in java. please assign this to hacktoberfest 22. and please add the label too.

**Comment by Meghwantsingh** [comment]
I would like to try this problem.

**Comment by arushi-2298** [comment]
i would like to work on this issue
plz assign me and label it

**Comment by Blazemas** [comment]
let me solve this issue , I have latest experience in this issue
#contribute

**Comment by Rising-tech** [comment]
i would like to solve this issue. Can you please assign this to me?
